azure identity  binding config
DEFRA/fcp-fd-probe pull request #4
Opened 2024-09-23 10:32 UTC by JungaBunga

2024-09-23 11:17 UTC, rtasalem requested changes, later dismissed
Changes need to be made as the `fcp-fd-auth` repo is being referenced in the Azure Identity and Azure Binding Identity. Should reference `fcp-fd-probe` instead.

2024-09-23 11:17 UTC, rtasalem commented on helm/fcp-fd-probe/templates/azure-identity-binding.yaml
> +{{- include "ffc-helm-library.azure-identity-binding" (list . "fcp-fd-auth.azure-identity-binding") -}}
Should reference the repo name so `fcp-fd-probe.azure-identity-binding` instead of `fcp-fd-auth.azure-identity-binding`.

2024-09-23 11:17 UTC, rtasalem commented on helm/fcp-fd-probe/templates/azure-identity-binding.yaml
> +{{- define "fcp-fd-auth.azure-identity-binding" -}}
Same as above - should reference the repo name.

2024-09-23 11:17 UTC, rtasalem commented on helm/fcp-fd-probe/templates/azure-identity.yaml
> +{{- include "ffc-helm-library.azure-identity" (list . "fcp-fd-auth.azure-identity") -}}
Should reference the repo name so `fcp-fd-probe.azure-identity` instead of `fcp-fd-auth.azure-identity`.

2024-09-23 11:17 UTC, rtasalem commented on helm/fcp-fd-probe/templates/azure-identity.yaml
> +{{- define "fcp-fd-auth.azure-identity" -}}
Same as above - should reference repo name.

2024-09-23 11:24 UTC, rtasalem submitted a review, later dismissed

2024-09-24 08:12 UTC, simonnineteen90 approved these changes

2024-09-26 07:22 UTC, merged